---
engines:
  phpmd:
    enabled: true
    config:
      file_extensions: "php,inc,module,install"
      rulesets: ".phpmd.xml"
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php,inc,module,install"
      encoding: utf-8
      standard: "Drupal"
      ignore_warnings: true
ratings:
  paths:
  - "**.php"
  - "**.inc"
  - "**.module"
  - "**.install"
exclude_paths:
