---
engines:
  phpmd:
    enabled: true
    config:
      file_extensions: "php,inc,module"
      rulesets: ".phpmd.xml"
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php,inc,module"
      encoding: utf-8
      standard: "Drupal"
      ignore_warnings: true
ratings:
  paths:
  - "includes/**.inc"
exclude_paths:
- "**/Test/**/*"
- misc
- modules
- profiles
- scripts
- sites
- themes
